sudo: false

# Build only master & PRs
branches:
  only:
    - master

language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

env:
  - WEBPACK_VERSION=2 MOCHA_VERSION=2
  - WEBPACK_VERSION=2 MOCHA_VERSION=3
  - WEBPACK_VERSION=3 MOCHA_VERSION=3
  - WEBPACK_VERSION=2 MOCHA_VERSION=4
  - WEBPACK_VERSION=3 MOCHA_VERSION=4

before_script:
  - "yarn add webpack@$WEBPACK_VERSION"
  - "yarn add mocha@$MOCHA_VERSION"

script:
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
